179816806 create post
BoutPure/twitter pull request #3
Opened 2022-06-14 16:42 UTC by mmyrtice

my tasks
[As User I can see my posts](https://www.pivotaltracker.com/story/show/179816806)
[As User I can make a Post](https://www.pivotaltracker.com/story/show/179816806)
+ comments

2022-06-15 10:44 UTC, AidarMingazov requested changes

2022-06-15 10:44 UTC, AidarMingazov commented on app/helpers/comments_helper.rb
> +module CommentsHelper
pls remove extra files

2022-06-15 10:44 UTC, AidarMingazov commented on app/helpers/posts_helper.rb
> +module PostsHelper
pls remove extra files

2022-06-15 10:44 UTC, AidarMingazov commented on app/models/comment.rb
> +class Comment < ApplicationRecord
pls remove extra

2022-06-15 10:44 UTC, AidarMingazov commented on app/models/concerns/visible.rb
> +end
pls add enter

2022-06-15 10:44 UTC, AidarMingazov commented on app/models/post.rb
> +
pls user Enum inside `include Visible`

2022-06-15 10:44 UTC, AidarMingazov commented on app/views/comments/_comment.html.erb
> +<% unless comment.archived? %>
extra file

2022-06-15 10:44 UTC, AidarMingazov commented on app/views/posts/edit.html.erb
> +<%= render "form", post: @post %>
end of file

2022-06-15 10:44 UTC, AidarMingazov commented on app/views/posts/_form.html.erb
> +<% end %>
end of file

2022-06-15 10:44 UTC, AidarMingazov commented on app/views/posts/new.html.erb
> +<%= render "form", post: @post %>
end of file

2022-06-15 10:44 UTC, AidarMingazov commented on config/routes.rb
> +    resources :comments
extra

2022-06-15 10:44 UTC, AidarMingazov commented on db/migrate/20220609123227_create_posts.rb
> +      t.text :body
add `status`

2022-06-15 10:44 UTC, AidarMingazov commented on db/migrate/20220609125616_create_comments.rb
> +class CreateComments < ActiveRecord::Migration[7.0]
extra

2022-06-15 10:44 UTC, AidarMingazov commented on db/migrate/20220609132936_add_status_to_comments.rb
> +class AddStatusToComments < ActiveRecord::Migration[7.0]
extra

2022-06-15 10:44 UTC, AidarMingazov commented on test/controllers/comments_controller_test.rb
> +require "test_helper"
extra

2022-06-15 10:44 UTC, AidarMingazov commented on test/controllers/posts_controller_test.rb
> +require "test_helper"
extra

2022-06-15 10:44 UTC, AidarMingazov commented on test/fixtures/comments.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
extra

2022-06-15 10:44 UTC, AidarMingazov commented on test/fixtures/posts.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
extra

2022-06-15 10:44 UTC, AidarMingazov commented on test/models/comment_test.rb
> +require "test_helper"
extra

2022-06-15 10:44 UTC, AidarMingazov commented on test/models/post_test.rb
> +require "test_helper"
extra

2022-06-15 13:34 UTC, BoutPure commented on db/migrate/20220609123227_create_posts.rb
> +      t.text :body
Added in separate migration

2022-06-15 16:53 UTC, BoutPure commented on app/models/post.rb
> +
I had put enum to posts without Visible module for now because I can't make it work inside one

2022-06-15 17:08 UTC, BoutPure approved these changes
I fix previous review comments.
Delete comments from project.
Add end file newlines.
Swap post statuses string array to enum.
Approved to merge.

2022-09-05 10:49 UTC, AidarMingazov requested changes

2022-09-05 10:49 UTC, AidarMingazov commented on app/controllers/posts_controller.rb
> +      @post = Post.find(params[:id])
extra tab

2022-09-05 10:49 UTC, AidarMingazov commented on app/controllers/posts_controller.rb
> +    p @post
what happen here ?

2022-09-05 10:49 UTC, AidarMingazov commented on app/models/concerns/visible.rb
> +module Visible
extra file

2022-09-13 19:19 UTC, merged